PROD:
  fill_this: later

TEST:
  SECRET_KEY: secret_key_set_with_randomly_generated_environment_variables_in_production
  DEBUG: True
  MONGODB_SETTINGS:
    authentication_source: admin
    host: mongodb+srv://cluster0-eyv1o.mongodb.net/flask?retryWrites=true&w=majority
    port: 27017
    username: verdantfox
    # We'll figure out a way to make this more secure later
    # (probably not password based with secret key stored elsewhere)
    password: DkVb8AJY!7u$
